#端口
server:
  port: 8090

http:
  pool:
    maxTotal: 20
    defaultMaxPerRoute: 10
  request:
    connectionRequestTimeout: 500
    connectTimeout: 5000
    socketTimeout: 30000
    staleConnectionCheckEnabled: true
    uri:
      iamp: http://192.168.1.27:8080/iamp
mount:
  distributemount: D://git/
  opticalmount: D://git/
  tapemount: D://git/
OpticalLib:
  opticalip: 192.168.100.199
  opticalport: 8000
  singleDiskCapacity: 23.3
  singleBoxCardNum: 25
TapeLib:
  webusername: shuju
  sessionKey: 69MOQca0Hv6NsOJH
Distribute:
  url: http://192.168.1.32:8000/